import { SearchBar } from "@/components/SearchBar";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { User } from "lucide-react";
// import { readFileAsync } from "@/context/actions/server/products";
import { InitialStateType, ProductProvider } from "@/context/productContext";
import { GetAllProducts, fetchCart } from "@/context/actions/client/products";
import { ProductValuesType } from "./upload/UploadContainer";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import Authentication from "@/components/AuthToggle";
import { getServerSession } from "next-auth/next";
import { authOptions } from "./api/auth/[...nextauth]/route";
import { AppSessionProvider } from "@/context/sessionProvider";
import ShoppingCartIcon from "@/components/shoppinCartIcon";
import { Toaster } from "@/components/ui/toaster";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ShoeMart",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
//   const data: InitialStateType = await readFileAsync();
//   const pd = data.products;
  const fetchedData = await GetAllProducts();
  const cart =  session && await fetchCart(session.id);
  const dataP: ProductValuesType[] = fetchedData.data;
  const state: InitialStateType = {
    products: [ ...dataP],
    cart: cart || {},
  };
  return (
    <html lang="en">
        <head>
        <Script src="/__ENV.js"></Script>
        </head>
      <body className={inter.className}>
        <AppSessionProvider session={session}>
          <ProductProvider data={state}>
            <div className="w-full">
              <div className="flex py-12 items-center justify-around">
                <Link href="/">
                  <h1 className="text-xl font-semibold sm:text-center">
                    ShoeMart
                  </h1>
                </Link>
                <div className="hidden md:flex md:gap-4 md:items-center">
                  <SearchBar />
                  <Link href="/cart">
                    <ShoppingCartIcon />
                  </Link>
                  <Link href="/profile">
                    <User />
                  </Link>
                  <Link href="/upload">
                    <Button variant="link">Upload</Button>
                  </Link>
                  <Authentication />
                </div>
              </div>
              {children}
            </div>
            <Toaster/>
          </ProductProvider>
        </AppSessionProvider>
      </body>
    </html>
  );
}
