name: TestBuild stage
on:
  push:
    branches:
    - master


env:
    NEXT_PUBLIC_Backend: "localhost"
    NEXTAUTH_SECRET: "12345"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Build with Docker
            run: |
              docker build  .